apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-with-docs
  description: The place to be, for great artists
  annotations:
      techdocs.io/documentation-url: "https://github.com/pladdha124/magital888/raw/master/service_with_docs/docs/index.md"
      techdocs.io/ref: "github.com/pladdha124/magital888/service_with_docs/docs"

spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
  techdocs:
    techdocs-ref:"https://github.com/pladdha124/magital888/tree/master/service_with_docs/docs"
