apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: magital888
  description: The place to be, for great artists
  annotations:
     backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: puja
